<?php
/******************************************************************************
 * NINA VIỆT NAM
 * Email: nina@nina.vn
 * Website: nina.vn
 * Version: 1.1.1
 * Date 18-09-2024
 * Đây là tài sản của CÔNG TY TNHH TM DV NINA. Vui lòng không sử dụng khi chưa được phép.
 */

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 208,
        'height' => 134,
        'thumb' => '208x134x1',
    ],
    'logoft' => [
        'title_main' => "Logo footer",
        'kind' => 'static',
        'title' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 160,
        'height' => 103,
        'thumb' => '160x103x1',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x1',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 870,
        'height' => 430,
        'thumb' => '870x430x1',
        'thumb2' => '500x248x1',
    ],
    'slide-qc' => [
        'title_main' => "Slide quảng cáo",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 320,
        'height' => 210,
        'thumb' => '320x210x1',
    ],
    'video' => [
        'title_main' => "Video",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'website' => [
            'title' => 'video'
        ],
        'routes' => true,
        'template' => 'video',
        'template-list' => 'video',
        'show_images' => false,
        'images' => false,
        'avatar' => false,
        'link_video' => true,
        'name' => true,
        'desc' => false,
        'width' => 37,
        'height' => 37,
        'thumb' => '37x37x2',
    ],
    'social' => [
        'title_main' => "Social left",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 40,
        'height' => 40,
        'thumb' => '40x40x2',
    ],
    'mangxahoi1' => [
        'title_main' => "Mạng xã hội header",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 42,
        'height' => 42,
        'thumb' => '42x42x2',
    ],
    'doitac' => [
        'title_main' => "Đối tác",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'website' => [
            'title' => 'doitac'
        ],
        'routes' => true,
        'template' => 'album',
        'template-list' => 'doitac',
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 190,
        'height' => 103,
        'thumb' => '190x103x1',
    ],
    'watermark_product' => [
        'title_main' => "Đóng dấu",
        'kind' => 'static',
        'watermark' =>true,
        'desc' => false,
        'title' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 70,
        'height' => 70,
        'thumb' => '70x70x1',
    ]
];